In [5]:
import numpy as np

x1 = np.array([[3, 12],
               [6, 3]])
x2 = np.array([[4, 13],
               [8, 2]])

r = np.hypot(x1, x2)
print(r)

[[ 5.         17.69180601]
 [10.          3.60555128]]


In [15]:
import numpy as np

trajectory = np.array([[1, 2],
                       [3, 4],
                       [5, 6],
                       [7, 8]])
ob = np.array([[3, 4],
               [1, 1]])


ox = ob[:, 0]
oy = ob[:, 1]
dx = trajectory[:, 0] - ox[:, None]
print("trajectory[:, 0].shape:", trajectory[:, 0].shape)
print("ox[:, None].shape:", ox[:, None].shape)
print("dx.shape:", dx.shape)
print(dx)
# dy = trajectory[:, 1] - oy[:, None]
# r = np.hypot(dx, dy)
# print("r.shape:", r.shape)

trajectory[:, 0].shape: (4,)
ox[:, None].shape: (2, 1)
dx.shape: (2, 4)
[[-2  0  2  4]
 [ 0  2  4  6]]


In [18]:
import numpy as np

x = np.array([[1, 2],
              [3, 4]])

b = np.array(x < 3)
print(b)

[[ True  True]
 [False False]]
[[ True  True]
 [False False]]
